Bank._IDb: 0
Bank._fD: 0
Broch.__IDs: 0
Capital.Deb10ratio: 1
Capital.F10: 2
Capital.F1max: 50
Capital.F1min: 50
Capital.L1rdMax: 0.2
Capital.L1shortMax: 1
Capital.NW10: 1000
Capital.Phi3: 0.1
Capital.Phi4: 0.9
Capital.alpha1: 3
Capital.alpha2: 2
Capital.beta1: 3
Capital.beta2: 4
Capital.d1: 0
Capital.gamma: 0.5
Capital.lastID1: 0
Capital.m1: 0.1
Capital.mu1: 0.08
Capital.n1: 4
Capital.nu: 0.04
Capital.pK0: 0
Capital.x1inf: -0.15
Capital.x1sup: 0.15
Capital.x5: 0.3
Capital.xi: 0.5
Capital.zeta1: 0.3
Capital.zeta2: 0.3
Cli.__IDc: 0
Cli.__nCan: 0
Cli.__nOrd: 0
Cli.__tOrd: 0
Cli.__tSel: 0
Cli1.__ID1: 0
Cli2.__ID2: 0
Consumption.Deb20ratio: 1
Consumption.F20: 3
Consumption.F2max: 200
Consumption.F2min: 200
Consumption.NW20: 1000
Consumption.Phi1: 0.1
Consumption.Phi2: 0.9
Consumption.b: 3
Consumption.bChg: 3
Consumption.chi: 1
Consumption.d2: 0
Consumption.e0: 1
Consumption.e0Chg: 1
Consumption.e1: 1
Consumption.e2: 1
Consumption.e3: 1
Consumption.e4: 1
Consumption.e5: 0.5
Consumption.e6: 1
Consumption.e7: 0.3
Consumption.e8: 0.3
Consumption.ent2HldPer: 100
Consumption.ent2HldShr: 0.5
Consumption.eta: 19
Consumption.f2minPosChg: 0
Consumption.f2trdChg: 0
Consumption.iota: 0.1
Consumption.kappaMax: 0.5
Consumption.kappaMin: 0
Consumption.lastID2: 0
Consumption.m2: 40
Consumption.mu20: 0.3
Consumption.mu20Chg: 0.3
Consumption.n2: 1
Consumption.omega1: 1
Consumption.omega2: 1
Consumption.omega3: 0
Consumption.pC0: 0
Consumption.u: 0.75
Consumption.upsilon: 0.04
Country.Crec: 0.2
Country.TregChg: 0
Country.flagAddWorkers: 0
Country.flagAllFirmsChg: 0
Country.flagCons: 1
Country.flagCreditRule: 0
Country.flagExpect: 0
Country.flagFireOrder1: 0
Country.flagFireOrder1Chg: 0
Country.flagFireOrder2: 0
Country.flagFireOrder2Chg: 0
Country.flagFireRule: 2
Country.flagFireRuleChg: 2
Country.flagFiscalRule: 0
Country.flagGovExp: 2
Country.flagHeterWage: 0
Country.flagHireOrder1: 0
Country.flagHireOrder1Chg: 0
Country.flagHireOrder2: 0
Country.flagHireOrder2Chg: 0
Country.flagHireSeq: 0
Country.flagHireSeqChg: 0
Country.flagIndexMinWage: 0
Country.flagIndexMinWageChg: 0
Country.flagIndexWage: 1
Country.flagIndexWageChg: 1
Country.flagLearn1: 0
Country.flagSearchDisc: 0
Country.flagSearchMode: 1
Country.flagSearchModeChg: 1
Country.flagTax: 0
Country.flagWageOffer: 0
Country.flagWageOfferChg: 1
Country.flagWagePremium: 0
Country.flagWorkerLBU: 0
Country.flagWorkerSkProd: 0
Country.gG: 0.005
Country.mLim: 1
Country.mPer: 1
Country.omicron: 0.5
Country.stick: 1
Country.tr: 0.1
Country.trChg: 0.1
Country.x2inf: -0.15
Country.x2sup: 0.15
Financial.B: 1
Financial.DebRule: 0.6
Financial.DefPrule: 0.03
Financial.EqB0: 1
Financial.Lambda: 2
Financial.Lambda0: 0
Financial.LambdaChg: 2
Financial.PhiB: 0.5
Financial.Trule: 100
Financial.Ut: 0.015
Financial.alphaB: 0.8
Financial.betaB: 1
Financial.dB: 0
Financial.deltaB: 1
Financial.deltaDeb: 0.05
Financial.gammaPi: 0
Financial.gammaU: 0
Financial.kConst: 0
Financial.mPerB: 4
Financial.muBonds: 0
Financial.muD: 1
Financial.muDeb: 0
Financial.muRes: 1
Financial.muResChg: 1
Financial.piT: 0
Financial.rAdj: 0.0025
Financial.rT: 0.01
Financial.rTchg: 0.01
Financial.rhoBonds: 0
Financial.tauB: 0.08
Financial.tauBchg: 0.08
Financial.thetaBonds: 12
Firm1._Eq1: 0
Firm1._ID1: 0
Firm1._bank1: 0
Firm1._pOrd1: 0
Firm1._t1ent: 0
Firm2._Eq2: 0
Firm2._ID2: 0
Firm2._bank2: 0
Firm2._pOrd2: 0
Firm2._postChg: 0
Firm2._t2ent: 0
Labor.Gamma: 0
Labor.GammaCost: 0.1
Labor.Ls0: 10
Labor.Lscale: 50
Labor.Tc: 1
Labor.Tp: 0
Labor.Tr: 120
Labor.Ts: 0
Labor.TsChg: 0
Labor.delta: 0
Labor.epsilon: 0.02
Labor.kappa: 1
Labor.lambda: 0.1
Labor.omega: 0
Labor.omegaPosChg: 0
Labor.omegaPreChg: 0
Labor.omegaU: 10
Labor.phi: 0.4
Labor.phiChg: 0.4
Labor.psi1: 0
Labor.psi2: 1
Labor.psi3: 0
Labor.psi4: 0.5
Labor.psi5: 0
Labor.psi6: 0
Labor.rho: 1
Labor.sigma: 0.5
Labor.tauG: 0
Labor.tauT: 0.01
Labor.tauU: 0.01
Labor.theta: 0
Labor.w0min: 1
Labor.wCap: 11
Stats.test1StEnd: 0
Stats.test1StIni: 1
Stats.test1idEnd: 3
Stats.test1idIni: 0
Stats.test1tEnd: 0
Stats.test1tIni: 1
Stats.test2StEnd: 0
Stats.test2StIni: 1
Stats.test2idEnd: 3
Stats.test2idIni: 0
Stats.test2tEnd: 0
Stats.test2tIni: 1
Stats.testCtEnd: 0
Stats.testCtIni: 1
Stats.testFtEnd: 0
Stats.testFtIni: 1
Stats.testLtEnd: 0
Stats.testLtIni: 1
Vint.__Avint: 0
Vint.__IDvint: 0
Vint.__nVint: 0
Vint.__pVint: 0
Vint.__tVint: 0
Vint.__toUseVint: 0
Worker._ID: 0
Worker._wfull: 0
Wrk1._IDw1: 0
Wrk1._key1: 0
Wrk2.__IDw2: 0
Wrk2.__key2: 0
WrkV.___IDwV: 0
