simulation: {}
objects:
  Root:
    parameters: {}
    variables:
      init: null
      runCountry: null
    functions: {}
    children:
    - Country
  Country:
    parameters:
      flagAddWorkers: 0.0
      flagAllFirmsChg: 0.0
      flagCons: 1.0
      flagCreditRule: 0.0
      flagExpect: 0.0
      flagFireOrder1: 0.0
      flagFireOrder1Chg: 0.0
      flagFireOrder2: 0.0
      flagFireOrder2Chg: 0.0
      flagFireRule: 2.0
      flagFireRuleChg: 2.0
      flagFiscalRule: 0.0
      flagGovExp: 2.0
      flagHeterWage: 0.0
      flagHireOrder1: 0.0
      flagHireOrder1Chg: 0.0
      flagHireOrder2: 0.0
      flagHireOrder2Chg: 0.0
      flagHireSeq: 0.0
      flagHireSeqChg: 0.0
      flagIndexMinWage: 0.0
      flagIndexMinWageChg: 0.0
      flagIndexWage: 1.0
      flagIndexWageChg: 1.0
      flagLearn1: 0.0
      flagSearchDisc: 0.0
      flagSearchMode: 1.0
      flagSearchModeChg: 1.0
      flagTax: 0.0
      flagWageOffer: 0.0
      flagWageOfferChg: 1.0
      flagWagePremium: 0.0
      flagWorkerLBU: 0.0
      flagWorkerSkProd: 0.0
      Crec: 0.2
      TregChg: 0.0
      gG: 0.005
      mLim: 1.0
      mPer: 1.0
      omicron: 0.5
      stick: 1.0
      tr: 0.1
      trChg: 0.1
      x2inf: -0.15
      x2sup: 0.15
    variables:
      A: null
      C: null
      Cd: null
      Creal: null
      Deb: null
      DebGDP: null
      Def: null
      DefP: null
      DefPgdp: null
      Div: null
      Eq: null
      G: null
      GDPnom: null
      GDPreal: null
      Sav: null
      SavAcc: null
      Tax: null
      TaxDiv: null
      cEntry: null
      cExit: null
      dAb: null
      dGDP: null
      entryExit: null
      initCountry: null
      regChg: null
      timeStep: null
    functions: {}
    children:
    - Financial
    - Labor
    - Capital
    - Consumption
    - Stats
  Financial:
    parameters:
      B: 1.0
      DebRule: 0.6
      DefPrule: 0.03
      EqB0: 1.0
      Lambda: 2.0
      LambdaChg: 2.0
      Lambda0: 0.0
      PhiB: 0.5
      Trule: 100.0
      Ut: 0.015
      alphaB: 0.8
      betaB: 1.0
      dB: 0.0
      deltaB: 1.0
      deltaDeb: 0.05
      gammaPi: 0.0
      gammaU: 0.0
      kConst: 0.0
      mPerB: 4.0
      muBonds: 0.0
      muD: 1.0
      muDeb: 0.0
      muRes: 1.0
      muResChg: 1.0
      piT: 0.0
      rAdj: 0.0025
      rT: 0.01
      rTchg: 0.01
      rhoBonds: 0.0
      tauB: 0.08
      tauBchg: 0.08
      thetaBonds: 12.0
    variables:
      BD: null
      BS: null
      BadDeb: null
      BadDeb1: null
      BadDeb2: null
      BondsB: null
      BondsCB: null
      Cl: null
      Depo: null
      DepoG: null
      DivB: null
      ExRes: null
      Gbail: null
      Loans: null
      LoansCB: null
      NWb: null
      PiB: null
      PiCB: null
      Res: null
      TaxB: null
      iB: null
      iDb: null
      r: null
      rBonds: null
      rD: null
      rDeb: null
      rRes: null
    functions:
      banksMaps: null
      cScores: null
      pickBank: null
    children:
    - Bank
  Bank:
    parameters:
      _IDb: 0.0
      _fD: 0.0
    variables:
      _BD: null
      _BadDeb1: null
      _BadDeb2: null
      _Bda: null
      _BondsB: null
      _CD1b: null
      _CD2b: null
      _Cl: null
      _Depo: null
      _DivB: null
      _ExRes: null
      _Gbail: null
      _Loans: null
      _LoansCB: null
      _NWb: null
      _PiB: null
      _Res: null
      _TC: null
      _TC1free: null
      _TC2free: null
      _TaxB: null
      _fB: null
      _iB: null
      _iDb: null
    functions:
      _cScores: null
    children:
    - Cli1
    - Cli2
  Cli1:
    parameters:
      __ID1: 0.0
    variables: {}
    functions: {}
    children: []
  Cli2:
    parameters:
      __ID2: 0.0
    variables: {}
    functions: {}
    children: []
  Labor:
    parameters:
      Gamma: 0.0
      GammaCost: 0.1
      Ls0: 250000.0
      Lscale: 50.0
      Tc: 1.0
      Tp: 0.0
      Tr: 120.0
      Ts: 0.0
      TsChg: 0.0
      delta: 0.0
      epsilon: 0.02
      kappa: 1.0
      lambda: 0.1
      omega: 0.0
      omegaPosChg: 0.0
      omegaPreChg: 0.0
      omegaU: 10.0
      phi: 0.4
      phiChg: 0.4
      psi1: 0.0
      psi2: 1.0
      psi3: 0.0
      psi4: 0.5
      psi5: 0.0
      psi6: 0.0
      rho: 1.0
      sigma: 0.5
      tauG: 0.0
      tauT: 0.01
      tauU: 0.01
      theta: 0.0
      w0min: 1.0
      wCap: 11.0
    variables:
      Bon: null
      Gtrain: null
      L: null
      Ls: null
      Ltrain: null
      TaxW: null
      TeAvg: null
      U: null
      Ue: null
      Us: null
      W: null
      appl: null
      dUeB: null
      sAvg: null
      sTavg: null
      sTmax: null
      sTmin: null
      sTsd: null
      sVavg: null
      sVsd: null
      searchProb: null
      wAvg: null
      wCent: null
      wMinPol: null
      wU: null
    functions: {}
    children:
    - Worker
  Worker:
    parameters:
      _ID: 0.0
      _wfull: 0.0
    variables:
      _Bon: null
      _CQ: null
      _Q: null
      _TaxW: null
      _Tc: null
      _Te: null
      _Tu: null
      _age: null
      _appl: null
      _dQb: null
      _discouraged: null
      _employed: null
      _s: null
      _sT: null
      _sV: null
      _searchProb: null
      _w: null
      _wR: null
      _wReal: null
      _wRes: null
      _wS: null
    functions: {}
    children: []
  Capital:
    parameters:
      Deb10ratio: 1.0
      F10: 50.0
      F1max: 50.0
      F1min: 50.0
      L1rdMax: 0.2
      L1shortMax: 1.0
      NW10: 1000.0
      Phi3: 0.1
      Phi4: 0.9
      alpha1: 3.0
      alpha2: 2.0
      beta1: 3.0
      beta2: 4.0
      d1: 0.0
      gamma: 0.5
      lastID1: 0.0
      m1: 0.1
      mu1: 0.08
      n1: 4.0
      nu: 0.04
      pK0: 0.0
      x1inf: -0.15
      x1sup: 0.15
      x5: 0.3
      xi: 0.5
      zeta1: 0.3
      zeta2: 0.3
    variables:
      A1: null
      D1: null
      Deb1: null
      Div1: null
      Eq1: null
      F1: null
      JO1: null
      L1: null
      L1d: null
      L1dRD: null
      L1rd: null
      MC1: null
      NW1: null
      PPI: null
      Pi1: null
      Q1: null
      Q1e: null
      S1: null
      Tax1: null
      W1: null
      cEntry1: null
      cExit1: null
      entry1: null
      entry1exit: null
      exit1: null
      dA1b: null
      fires1: null
      hires1: null
      i1: null
      iD1: null
      imi: null
      inn: null
      p1avg: null
      quits1: null
      retires1: null
      sT1min: null
      w1avg: null
    functions:
      f1rescale: null
    children:
    - Firm1
    - Wrk1
  Firm1:
    parameters:
      _Eq1: 0.0
      _ID1: 0.0
      _bank1: 0.0
      _pOrd1: 0.0
      _t1ent: 0.0
    variables:
      _Atau: null
      _Btau: null
      _BC: null
      _CD1: null
      _CD1c: null
      _CS1: null
      _D1: null
      _Deb1: null
      _Deb1max: null
      _Div1: null
      _HC: null
      _L1: null
      _L1d: null
      _L1dRD: null
      _L1rd: null
      _NC: null
      _NW1: null
      _NW1p: null
      _Pi1: null
      _Q1: null
      _Q1e: null
      _RD: null
      _S1: null
      _Tax1: null
      _W1: null
      _c1: null
      _f1: null
      _i1: null
      _iD1: null
      _imi: null
      _inn: null
      _p1: null
      _qc1: null
    functions:
      _CS1a: null
    children:
    - Cli
  Cli:
    parameters:
      __IDc: 0.0
      __nCan: 0.0
      __nOrd: 0.0
      __tOrd: 0.0
      __tSel: 0.0
    variables: {}
    functions: {}
    children: []
  Wrk1:
    parameters:
      _IDw1: 0.0
      _key1: 0.0
    variables: {}
    functions: {}
    children: []
  Consumption:
    parameters:
      Deb20ratio: 1.0
      F20: 200.0
      F2max: 200.0
      F2min: 200.0
      NW20: 1000.0
      Phi1: 0.1
      Phi2: 0.9
      b: 3.0
      bChg: 3.0
      chi: 1.0
      d2: 0.0
      e0: 1.0
      e0Chg: 1.0
      e1: 1.0
      e2: 1.0
      e3: 1.0
      e4: 1.0
      e5: 0.5
      e6: 1.0
      e7: 0.3
      e8: 0.3
      ent2HldPer: 100.0
      ent2HldShr: 0.5
      eta: 19.0
      f2min: 1.0e-05
      f2minPosChg: 0.0
      f2trdChg: 0.0
      iota: 0.1
      kappaMax: 0.5
      kappaMin: 0.0
      lastID2: 0.0
      m2: 40.0
      mu20: 0.3
      mu20Chg: 0.3
      n2: 1.0
      omega1: 1.0
      omega2: 1.0
      omega3: 0.0
      pC0: 0.0
      u: 0.75
      upsilon: 0.04
    variables:
      A2: null
      A2p: null
      Bon2: null
      CI: null
      CPI: null
      Deb2: null
      Div2: null
      D2: null
      D2d: null
      D2e: null
      Eavg: null
      EI: null
      Eq2: null
      F2: null
      Id: null
      Inom: null
      Ireal: null
      JO2: null
      K: null
      Kd: null
      Knom: null
      L2: null
      L2d: null
      MC2: null
      N: null
      NW2: null
      Pi2: null
      Pi2rateAvg: null
      Q2: null
      Q2d: null
      Q2e: null
      Q2p: null
      Q2u: null
      SI: null
      S2: null
      Tax2: null
      W2: null
      c2: null
      c2e: null
      cEntry2: null
      cExit2: null
      dCPI: null
      dCPIb: null
      dNnom: null
      entry2: null
      entry2exit: null
      exit2: null
      f2critChg: null
      f2posChg: null
      fires2: null
      hires2: null
      i2: null
      iD2: null
      l2avg: null
      l2max: null
      l2min: null
      oldVint: null
      p2avg: null
      p2max: null
      p2min: null
      q2avg: null
      q2max: null
      q2min: null
      quits2: null
      retires2: null
      sV2avg: null
      w2avg: null
      w2oAvg: null
      w2oMax: null
      w2realAvg: null
    functions:
      f2rescale: null
      firm2maps: null
    children:
    - Firm2
  Firm2:
    parameters:
      _Eq2: 0.0
      _ID2: 0.0
      _bank2: 0.0
      _pOrd2: 0.0
      _postChg: 0.0
      _t2ent: 0.0
    variables:
      _A2: null
      _A2p: null
      _Bon2: null
      _CD2: null
      _CD2c: null
      _CI: null
      _CS2: null
      _D2: null
      _D2d: null
      _D2e: null
      _Deb2: null
      _Deb2max: null
      _Div2: null
      _E: null
      _EI: null
      _EId: null
      _Inom: null
      _JO2: null
      _K: null
      _Kd: null
      _Knom: null
      _L2: null
      _L2d: null
      _L2vac: null
      _N: null
      _NW2: null
      _NW2p: null
      _Pi2: null
      _Pi2rate: null
      _Q2: null
      _Q2d: null
      _Q2e: null
      _Q2p: null
      _Q2pe: null
      _Q2u: null
      _RS2: null
      _SI: null
      _SId: null
      _S2: null
      _Tax2: null
      _W2: null
      _alloc2: null
      _c2: null
      _c2e: null
      _dA2b: null
      _dNnom: null
      _dQ2d: null
      _f2: null
      _fires2: null
      _hires2: null
      _i2: null
      _iD2: null
      _l2: null
      _life2cycle: null
      _mu2: null
      _oldVint: null
      _p2: null
      _q2: null
      _qc2: null
      _quits2: null
      _retires2: null
      _s2avg: null
      _sT2min: null
      _supplier: null
      _w2avg: null
      _w2o: null
      _w2realAvg: null
    functions:
      _CS2a: null
    children:
    - Broch
    - Vint
    - Wrk2
  Broch:
    parameters:
      __IDs: 0.0
    variables: {}
    functions: {}
    children: []
  Vint:
    parameters:
      __Avint: 0.0
      __IDvint: 0.0
      __nVint: 0.0
      __pVint: 0.0
      __tVint: 0.0
      __toUseVint: 0.0
    variables:
      __AeVint: null
      __Qvint: null
      __RSvint: null
      __dLdVint: null
    functions: {}
    children:
    - WrkV
  WrkV:
    parameters:
      ___IDwV: 0.0
    variables: {}
    functions: {}
    children: []
  Wrk2:
    parameters:
      __IDw2: 0.0
      __key2: 0.0
    variables: {}
    functions: {}
    children: []
  Stats:
    parameters:
      testCtIni: 1.0
      testCtEnd: 0.0
      testFtIni: 1.0
      testFtEnd: 0.0
      testLtIni: 1.0
      testLtEnd: 0.0
      test1StIni: 1.0
      test1StEnd: 0.0
      test2StIni: 1.0
      test2StEnd: 0.0
      test1tIni: 1.0
      test1tEnd: 0.0
      test1idIni: 0.0
      test1idEnd: 3.0
      test2tIni: 1.0
      test2tEnd: 0.0
      test2idIni: 0.0
      test2idEnd: 3.0
    variables:
      testSFC: null
      testCountry: null
      testFin: null
      testLabor: null
      test1sec: null
      test2sec: null
      test1firm: null
      test2firm: null
    functions: {}
    children:
    - Mac
    - Sec
    - Lab
  Mac:
    parameters: {}
    variables:
      CD: null
      CDc: null
      CS: null
      DefGDP: null
      GDI: null
      GDPdefl: null
      Gini: null
      TC: null
      dA: null
    functions: {}
    children: []
  Sec:
    parameters: {}
    variables:
      A2posChg: null
      A2preChg: null
      A2sd: null
      A2sdPosChg: null
      A2sdPreChg: null
      AtauAvg: null
      B2payers: null
      Bda: null
      Bfail: null
      BadDebAcc: null
      BtauAvg: null
      CD1: null
      CD1c: null
      CD2: null
      CD2c: null
      CS1: null
      CS2: null
      Deb1max: null
      Deb2max: null
      EId: null
      HCavg: null
      HHb: null
      HH1: null
      HH2: null
      HPb: null
      HP1: null
      HP2: null
      NCavg: null
      RD: null
      RS2: null
      SId: null
      age1avg: null
      age2avg: null
      dN: null
      exit1fail: null
      exit2fail: null
      mu2avg: null
      nBrochAvg: null
      noWrk2: null
      q2posChg: null
      q2preChg: null
      s1avg: null
      s2avg: null
    functions: {}
    children: []
  Lab:
    parameters: {}
    variables:
      InAvg: null
      InAvgReal: null
      InLogSD: null
      InMax: null
      InMin: null
      Lent: null
      Lexit: null
      L1ent: null
      L1exit: null
      L1v: null
      L2ent: null
      L2exit: null
      L2larg: null
      L2v: null
      TuAvg: null
      V: null
      dw: null
      part: null
      w2avgLarg: null
      w2oMin: null
      w2realPosChg: null
      w2realPreChg: null
      wAvgReal: null
      wGini: null
      wLogSD: null
      wMax: null
      wMin: null
      wrAvg: null
      wrLogSD: null
      wrMax: null
      wrMin: null
      wsAvg: null
      wsLogSD: null
      wsMax: null
      wsMin: null
    functions: {}
    children: []
